### ISSUE TITLE
inputdata link_dirtree is not supported anymore

### ISSUE THREAD

**Issue by devarajun** [MetOs-UiO/CTSM-Norway-Documentation#14]
Anyone tested if link_dirtree is working? I see that in September 2020 the Keith Oleson of NCAR  mentions it's not supported anymore. See his reply here: https://bb.cgd.ucar.edu/cesm/threads/where-is-the-path-of-link_dirtree-in-clm5-0-06.5596/#post-37826

**Comment by sunnivin** [comment]
This question is related to #12 and I agree that it does not seem right to use `link_dirtree` in our documentation.  

I prefer we keep the discussion in one place so I will close this issue.
