### ISSUE TITLE
NUOPC coupler for fram

### ISSUE THREAD

**Issue by mvdebolskiy** [MetOs-UiO/CTSM-Norway-Documentation#26]
Hi, if anyone of you wants to run CTSM with a different coupler (NUOPC) for example

when you `./create_newcase` you should specify an option `-driver nuopc`

It will give you errors associated with ESMF, I am in progress of working it out.

This means that `config_` files will need to be updated.

**Comment by sunnivin** [comment]
Thank you for adding an issue about this! 

Looking forward to see your suggestions:)

**Comment by mvdebolskiy** [comment]
I've managed to build newer ESMF version (8.1.1) that is needed for the current NUOPC implementation in CTSM with easybuild locally for my account.
Sigma2 support answered that they will add a new version soon when they get a new intel toolchain to be a global module for fram.

**Comment by ziu1986** [comment]
ESMF version 8.2.0 is now available on fram but not on saga. ESMF is also required to build WRF-CTSM with LILAC.
If necessary, we should ask for an update on saga, too.

**Comment by mvdebolskiy** [comment]
Current working .cime config files for FRAM to run latest master CTSM with nuopc  latest master are available here:
https://github.com/mvdebolskiy/dotcimefram
