### ISSUE TITLE
Do we want the documentation to show concepts or exact? 

### ISSUE THREAD

**Issue by sunnivin** [MetOs-UiO/CTSM-Norway-Documentation#3]
The main target for our documentation is our future selves and new team members. 

I imagine that it can be hard for a new student to follow the documentation steps if they do not show where the commands should be executed. 

Would it be better to write: 
```
[~/HOME/CTSM]$ ./manage_externals/checkout_externals
```
instead of 
```
./manage_externals/checkout_externals
```
? 

The copy-paste functionality of the sphinx docs (in the upper right corner of a code block) can't be used in the latter case.

**Comment by ziu1986** [comment]
In principle, I like the idea of showing where a command should be executed - else you would need to add a line `cd $CTSM_ROOT` e.g.

**Comment by ecaas** [comment]
I agree that it should be included. I like the idea to add a line that specifies the path, then you will still keep the copy-paste functionality.

**Comment by devarajun** [comment]
I agree too, exact is better than the concept.

**Comment by lasseke** [comment]
Agreed, nice to include full paths for clarity!

**Comment by sunnivin** [comment]
Thank you for your input! I think we agree that it makes sense to be explicit. 

@emiliano-gelati made a nice remark: should we go for `$HOME` or `HOME`? To be a bit clearer; should we explicitly use environmental path variables or is it fine to explain once that `HOME`=your/home/directory once? For a beginner I think that the difference between the two can be very confusing.

**Comment by ziu1986** [comment]
I consider this issue closed.
